#pragma strict_types

void
create()
{
    sprintf("%O", ({ "a", "b", 1, 2, this_object(), previous_object(), 
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object(),
		  ({ "a", "b", 1, 2, this_object(), previous_object()
		}) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) })
		}) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) })
		}) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) })
		}) }) }) }) }) }) }) }));
}
