#pragma strict_types

int watchmecrashthisdriverwithareallyreallyreallyreallyreallreallyreallyreallyreallyreallyreallyreallyreallyreallreallylongfunctionnameohitneedstobereallyreallyreallylongofcoursebutIcandoityesicanithinkicanithinkicaniknowicaniknowcanhahahahahabutthisisreallyboringsozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz(int x);

void
create()
{
}
